/* generated by scripts/codegen */
import type {
  Config,
  GetEnsAddressErrorType,
  ResolvedRegister,
} from '@wagmi/core'
import type { Compute } from '@wagmi/core/internal'
import {
  type GetEnsAddressData,
  type GetEnsAddressOptions,
  type GetEnsAddressQueryFnData,
  type GetEnsAddressQueryKey,
  getEnsAddressQueryOptions,
} from '@wagmi/core/query'
import { computed } from 'vue'
import type { ConfigParameter, QueryParameter } from '../types/properties.js'
import type { DeepMaybeRef } from '../types/ref.js'
import { deepUnref } from '../utils/cloneDeep.js'
import { type UseQueryReturnType, useQuery } from '../utils/query.js'
import { useChainId } from './useChainId.js'
import { useConfig } from './useConfig.js'

export type UseEnsAddressParameters<
  config extends Config = Config,
  selectData = GetEnsAddressData,
> = Compute<
  DeepMaybeRef<
    GetEnsAddressOptions<config> &
      ConfigParameter<config> &
      QueryParameter<
        GetEnsAddressQueryFnData,
        GetEnsAddressErrorType,
        selectData,
        GetEnsAddressQueryKey<config>
      >
  >
>

export type UseEnsAddressReturnType<selectData = GetEnsAddressData> =
  UseQueryReturnType<selectData, GetEnsAddressErrorType>

/** https://wagmi.sh/vue/api/composables/useEnsAddress */
export function useEnsAddress<
  config extends Config = ResolvedRegister['config'],
  selectData = GetEnsAddressData,
>(
  parameters: UseEnsAddressParameters<config, selectData> = {},
): UseEnsAddressReturnType<selectData> {
  const params = computed(() => deepUnref(parameters))
  const config = useConfig(params)
  const chainId = useChainId({ config })
  const options = computed(() => {
    const { query = {} } = params.value
    const options = getEnsAddressQueryOptions(config, {
      ...params.value,
      chainId: params.value.chainId ?? chainId.value,
    })
    return {
      ...query,
      ...options,
      enabled: Boolean(options.enabled && (query.enabled ?? true)),
    }
  })
  return useQuery(options as any) as UseEnsAddressReturnType<selectData>
}
