import { camelCase } from 'change-case'
import type { FSWatcher, WatchOptions } from 'chokidar'
import { default as dedent } from 'dedent'
import { default as fse } from 'fs-extra'

import type { Contract, ContractSource, Watch } from '../config'
import * as logger from '../logger'
import { findConfig, resolveConfig } from '../utils'

export type Generate = {
  config?: string
  root?: string
}

type ContractResult = Contract & {
  content: string
}

export async function generate(options: Generate) {
  const configPath = await findConfig(options)
  if (!configPath) throw new Error(`Config not found at "${configPath}"`)
  const resolvedConfig = await resolveConfig({ configPath })

  const contracts = new Map<string, ContractResult>()
  const watchConfigs: Watch[] = []
  for (const config of resolvedConfig.contracts) {
    if ('contracts' in config) {
      const resolvedContracts = await config.contracts()
      resolvedConfig.contracts.push(...resolvedContracts)
      if (config.watch) watchConfigs.push(config.watch)
      continue
    }

    logger.log(`Fetching ABI for ${config.name}…`)
    if (contracts.has(config.name))
      throw new Error(`Contract name "${config.name}" is not unique.`)
    const contract = await getContract(config)
    contracts.set(config.name, contract)
  }

  // Write output to file
  await writeContracts(Array.from(contracts.values()))
  if (!watchConfigs.length) return

  // Watch for changes
  const { watch } = await import('chokidar')
  let timeout: NodeJS.Timeout | null
  const delay = 100
  const watchers: FSWatcher[] = []
  const watchOptions: WatchOptions = {
    atomic: true,
    awaitWriteFinish: true,
    ignoreInitial: true,
    persistent: true,
  }
  for (const watchConfig of watchConfigs) {
    const watcher = watch(watchConfig.paths, watchOptions)
    watcher.on('all', async (event, path) => {
      if (event !== 'change' && event !== 'add' && event !== 'unlink') return

      let needsWrite = false
      if (event === 'change') {
        const contractConfig = await watchConfig.onChange(path)
        if (!contractConfig) return
        contracts.set(contractConfig.name, await getContract(contractConfig))
        needsWrite = true
      } else if (event === 'add') {
        const contractConfig = await watchConfig.onAdd?.(path)
        if (!contractConfig) return
        contracts.set(contractConfig.name, await getContract(contractConfig))
        needsWrite = true
      } else if (event === 'unlink') {
        const name = await watchConfig.onRemove?.(path)
        if (!name) return
        contracts.delete(name)
        needsWrite = true
      }

      // Debounce writes
      if (needsWrite) {
        if (timeout) clearTimeout(timeout)
        timeout = setTimeout(async () => {
          console.log('Saving…')
          timeout = null
          await writeContracts(Array.from(contracts.values()))
          console.log('Saving!')
        }, delay)
        needsWrite = false
      }
    })
    watcher.on('ready', async () => {
      if (watchConfig.command) {
        console.log(`Running watch command: ${watchConfig.command}`)
        const [command, ...parts] = watchConfig.command.split(' ')
        const { execa } = await import('execa')
        await execa(command!, parts).stdout?.pipe(process.stdout)
      }
    })

    watchers.push(watcher)
  }

  // Watch `@wagmi/cli` config file for changes
  watch(configPath).on('change', async (path) => {
    const { basename } = await import('pathe')
    logger.log(
      `> Found a change in ${basename(
        path,
      )}. Restart for changes to take effect.`,
    )
  })

  // Display message and close watchers on Ctrl+C exit
  process.once('SIGINT', shutdown)
  process.once('SIGTERM', shutdown)
  function shutdown() {
    logger.log('Shutting down watch…')
    for (const watcher of watchers) {
      watcher.close()
    }
  }
}

async function getContract({ abi: source, address, name }: ContractSource) {
  let abi
  if (typeof source === 'function') {
    try {
      abi = await source({ address })
    } catch (error) {
      throw new Error(`Failed to fetch contract ABI for ${name}`)
    }
  } else abi = source

  const abiName = `${camelCase(name)}ABI`
  const addressName = `${camelCase(name)}Address`
  let content = dedent`
    export const ${abiName} = ${JSON.stringify(source)} as const
  `
  if (address) {
    const configName = `${camelCase(name)}Config`
    content = dedent`
      ${content}
      export const ${addressName} = ${JSON.stringify(address)} as const
      export const ${configName} = { address: ${addressName}, abi: ${abiName} } as const
    `
  }

  return { abi, address, content, name } as const
}

async function writeContracts(
  contracts: ContractResult[],
  filename = 'wagmi-generated',
) {
  // Assemble content
  let content = dedent`
    // Generated by @wagmi/cli
    // ${new Date().toISOString()}
  `
  for (const contract of contracts) {
    content = dedent`
      ${content}

      ${contract.content}
    `
  }

  // Format and write output
  const cwd = process.cwd()
  const outPath = `${cwd}/src/${filename}.ts`
  const dprint = (await import('dprint-node')).default
  const formatted = await dprint.format(outPath, content, {
    bracePosition: 'nextLine',
    quoteProps: 'asNeeded',
    quoteStyle: 'alwaysSingle',
    semiColons: 'asi',
    trailingCommas: 'onlyMultiLine',
  })
  await fse.writeFile(outPath, formatted, {})
}
