auditConfig:
  ignoreGhsas:
    - GHSA-29xp-372q-xqph
    - GHSA-5j98-mcp5-4vw2
    - GHSA-93m4-6634-74q7
    - GHSA-ffrw-9mx8-89p8 
    - GHSA-g3ch-rx76-35fx 
    - GHSA-mh29-5h37-fv8m
    - GHSA-qpm2-6cq5-7pq5
    - GHSA-vjh7-7g9h-fjfh 
catalog:
  "@vitejs/plugin-react": "^4.3.3"
  "@tanstack/query-core": "5.49.1"
  "@tanstack/react-query": "5.49.2"
  "@tanstack/vue-query": "5.49.1"
  "@types/react": "18.3.1"
  "@types/react-dom": "18.3.0"
  react-dom: "18.3.1"
  react: "18.3.1"
  vue: "3.4.27"
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@gemini-wallet/core"
  - "@wagmi/cli"
  - "@wagmi/connectors"
  - "@wagmi/core"
  - "@wagmi/test"
  - "@wagmi/vue"
  - porto
  - wagmi
packages:
  - packages/*
  - "!packages/register-tests"
  - packages/cli/src/plugins/__fixtures__/hardhat
  - packages/register-tests/*
  - playgrounds/*
  - site
