catalog:
  "@vitejs/plugin-react": "^4.3.3"
  "@tanstack/query-core": "5.49.1"
  "@tanstack/react-query": "5.49.2"
  "@tanstack/vue-query": "5.49.1"
  "@types/react": "18.3.1"
  "@types/react-dom": "18.3.0"
  react-dom: "18.3.1"
  react: "18.3.1"
  vue: "3.4.27"
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@wagmi/cli"
  - "@wagmi/connectors"
  - "@wagmi/core"
  - "@wagmi/test"
  - "@wagmi/vue"
  - porto
  - wagmi
packages:
  - packages/*
  - "!packages/register-tests"
  - packages/cli/src/plugins/__fixtures__/hardhat
  - packages/register-tests/*
  - playgrounds/*
  - site
