auditConfig:
  ignoreGhsas:
    - GHSA-g3ch-rx76-35fx # vue-template-compiler@>=2.0.0 <3.0.0
    - GHSA-ffrw-9mx8-89p8 # fast-redact@<=3.5.0
    - GHSA-qpm2-6cq5-7pq5 # happy-dom@<20.0.2
    - GHSA-93m4-6634-74q7 # vite@>=7.1.0 <=7.1.10
    - GHSA-29xp-372q-xqph # tar@=7.5.1
    - GHSA-mh29-5h37-fv8m # js-yaml@>=4.1.1
    - GHSA-5j98-mcp5-4vw2 # glob>=11.1.0
autoInstallPeers: false
catalog:
  '@base-org/account': 2.4.0
  '@coinbase/wallet-sdk': 4.3.6
  '@gemini-wallet/core': 0.3.2
  '@metamask/sdk': 0.33.1
  '@nuxt/schema': 4.2.1
  '@safe-global/safe-apps-provider': 0.18.6
  '@safe-global/safe-apps-sdk': 9.1.0
  '@tanstack/query-core': 5.49.1
  '@tanstack/react-query': 5.49.2
  '@tanstack/solid-query': 5.49.1
  '@tanstack/vue-query': 5.49.1
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^4.3.3
  '@vitejs/plugin-vue': 6.0.1
  '@walletconnect/ethereum-provider': 2.21.1
  buffer: 6.0.3
  ox: 0.11.1
  nuxt: 4.2.1
  porto: 0.2.35
  react: 19.2.0
  react-dom: 19.2.0
  solid-js: 1.9.10
  vite: 7.2.2
  vite-plugin-solid: 2.11.10
  vue: 3.4.27
linkWorkspacePackages: deep
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@isaacs/brace-expansion' # TODO: remove after 2026-02-05
  - '@gemini-wallet/core'
  - '@wagmi/cli'
  - '@wagmi/connectors'
  - '@wagmi/core'
  - '@wagmi/test'
  - '@wagmi/solid'
  - '@wagmi/vue'
  - abitype
  - ox
  - porto
  - prool
  - wagmi
  - viem
overrides:
  '@isaacs/brace-expansion@<=5.0.0': 5.0.1
  cookie@<0.7.0: 0.7.0
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  devalue@>=5.1.0 <5.6.2: 5.6.2
  devalue@>=5.3.0 <=5.6.1: 5.6.2
  diff@<8.0.3: 8.0.3
  elliptic@<=6.6.0: '>=6.6.1'
  esbuild@<=0.24.2: 0.25.0
  glob@>=10.2.0 <10.5.0: 10.5.0
  h3@<=1.15.4: 1.15.5
  happy-dom@<20.0.2: '>=20.0.2'
  hono@<4.11.7: 4.11.7
  mdast-util-to-hast@<13.2.1: '>=13.2.1'
  nanoid@<3.3.8: 3.3.8
  node-forge@<1.3.2: '>=1.3.2'
  semver@<5.7.2: '>=5.7.2'
  serialize-javascript@>=6.0.0 <6.0.2: 6.0.2
  seroval@<1.4.1: '>=1.4.1'
  tar@<=7.5.6: 7.5.7
  tmp@<=0.2.3: 0.2.4
  undici@<6.23.0: 6.23.0
  undici@>=7.0.0 <7.18.2: 7.18.2
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  wrangler@>=4.0.0 <4.59.1: '>=4.59.1'
  ws@>=8.0.0 <8.17.1: 8.17.1
packages:
  - packages/*
  - '!packages/register-tests'
  - packages/cli/src/plugins/__fixtures__/hardhat
  - packages/register-tests/*
  - playgrounds/*
  - site
peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - react
    - react-native
    - search-insights
trustPolicy: no-downgrade
trustPolicyExclude:
  - '@coinbase/cdp-sdk@1.38.4'
  - '@noble/curves@1.8.0'
  - '@noble/hashes@1.7.0'
  - chokidar@4.0.3
  - semver@6.3.1
  - undici@6.22.0
  - vite@5.4.21 || 6.4.1
