import { renderPrimitive } from '@wagmi/test/solid'
import { expect, test } from 'vitest'

import * as query from './query.js'

test('exports', () => {
  expect(Object.keys(query)).toMatchInlineSnapshot(`
    [
      "callQueryKey",
      "callQueryOptions",
      "connectMutationOptions",
      "deployContractMutationOptions",
      "disconnectMutationOptions",
      "estimateFeesPerGasQueryKey",
      "estimateFeesPerGasQueryOptions",
      "estimateGasQueryKey",
      "estimateGasQueryOptions",
      "estimateMaxPriorityFeePerGasQueryKey",
      "estimateMaxPriorityFeePerGasQueryOptions",
      "getBalanceQueryKey",
      "getBalanceQueryOptions",
      "getBlobBaseFeeQueryKey",
      "getBlobBaseFeeQueryOptions",
      "getBlockNumberQueryKey",
      "getBlockNumberQueryOptions",
      "getBlockQueryKey",
      "getBlockQueryOptions",
      "getBlockTransactionCountQueryKey",
      "getBlockTransactionCountQueryOptions",
      "getBytecodeQueryKey",
      "getBytecodeQueryOptions",
      "getCallsStatusQueryKey",
      "getCallsStatusQueryOptions",
      "getCapabilitiesQueryKey",
      "getCapabilitiesQueryOptions",
      "getConnectorClientQueryKey",
      "getConnectorClientQueryOptions",
      "getContractEventsQueryKey",
      "getContractEventsQueryOptions",
      "getEnsAddressQueryKey",
      "getEnsAddressQueryOptions",
      "getEnsAvatarQueryKey",
      "getEnsAvatarQueryOptions",
      "getEnsNameQueryKey",
      "getEnsNameQueryOptions",
      "getEnsResolverQueryKey",
      "getEnsResolverQueryOptions",
      "getEnsTextQueryKey",
      "getEnsTextQueryOptions",
      "getFeeHistoryQueryKey",
      "getFeeHistoryQueryOptions",
      "getGasPriceQueryKey",
      "getGasPriceQueryOptions",
      "getProofQueryKey",
      "getProofQueryOptions",
      "getStorageAtQueryKey",
      "getStorageAtQueryOptions",
      "getTransactionConfirmationsQueryKey",
      "getTransactionConfirmationsQueryOptions",
      "getTransactionCountQueryKey",
      "getTransactionCountQueryOptions",
      "getTransactionQueryKey",
      "getTransactionQueryOptions",
      "getTransactionReceiptQueryKey",
      "getTransactionReceiptQueryOptions",
      "getWalletClientQueryKey",
      "getWalletClientQueryOptions",
      "hashFn",
      "infiniteReadContractsQueryKey",
      "infiniteReadContractsQueryOptions",
      "prepareTransactionRequestQueryKey",
      "prepareTransactionRequestQueryOptions",
      "readContractQueryKey",
      "readContractQueryOptions",
      "readContractsQueryKey",
      "readContractsQueryOptions",
      "reconnectMutationOptions",
      "sendCallsMutationOptions",
      "sendCallsSyncMutationOptions",
      "sendTransactionMutationOptions",
      "sendTransactionSyncMutationOptions",
      "showCallsStatusMutationOptions",
      "signMessageMutationOptions",
      "signTransactionMutationOptions",
      "signTypedDataMutationOptions",
      "simulateContractQueryKey",
      "simulateContractQueryOptions",
      "structuralSharing",
      "switchAccountMutationOptions",
      "switchChainMutationOptions",
      "switchConnectionMutationOptions",
      "useInfiniteQuery",
      "useMutation",
      "useQuery",
      "verifyMessageQueryKey",
      "verifyMessageQueryOptions",
      "verifyTypedDataQueryKey",
      "verifyTypedDataQueryOptions",
      "waitForCallsStatusQueryKey",
      "waitForCallsStatusQueryOptions",
      "waitForTransactionReceiptQueryKey",
      "waitForTransactionReceiptQueryOptions",
      "watchAssetMutationOptions",
      "writeContractMutationOptions",
      "writeContractSyncMutationOptions",
    ]
  `)
})

test('useInfiniteQuery exposes its query key', () => {
  const queryKey = ['example', { page: 1 }] as const
  const { result, cleanup } = renderPrimitive(() =>
    query.useInfiniteQuery(() => ({
      queryKey,
      queryFn: async () => 'value',
      initialPageParam: 0,
      getNextPageParam: () => undefined,
    })),
  )

  expect(result.queryKey).toEqual(queryKey)
  cleanup()
})
