import * as Exports from './'

it('should expose correct exports', () => {
  expect(Object.keys(Exports)).toEqual([
    'Connector',
    'InjectedConnector',
    'Provider',
    'WalletConnectConnector',
    'WalletLinkConnector',
    'chain',
    'defaultChains',
    'defaultL2Chains',
    'developmentChains',
    'erc1155ABI',
    'erc20ABI',
    'erc721ABI',
    'normalizeChainId',
    'normalizeMessage',
    'useAccount',
    'useBalance',
    'useBlockNumber',
    'useConnect',
    'useContext',
    'useContract',
    'useContractEvent',
    'useEnsAvatar',
    'useEnsLookup',
    'useEnsResolver',
    'useFeeData',
    'useNetwork',
    'useProvider',
    'useSignMessage',
    'useToken',
    'useWebSocketProvider',
    'verifyNormalizedMessage',
  ])
})
