/* generated by scripts/codegen */
import {
  type GetGasPriceErrorType as viem_GetGasPriceErrorType,
  type GetGasPriceParameters as viem_GetGasPriceParameters,
  type GetGasPriceReturnType as viem_GetGasPriceReturnType,
  getGasPrice as viem_getGasPrice,
} from 'viem/actions'
import type { Config } from '../createConfig.js'
import type { ChainIdParameter } from '../types/properties.js'
import type { Compute } from '../types/utils.js'
import { getAction } from '../utils/getAction.js'

export type GetGasPriceParameters<
  config extends Config = Config,
  chainId extends
    config['chains'][number]['id'] = config['chains'][number]['id'],
> = Compute<viem_GetGasPriceParameters & ChainIdParameter<config, chainId>>

export type GetGasPriceReturnType = viem_GetGasPriceReturnType

export type GetGasPriceErrorType = viem_GetGasPriceErrorType

/** https://wagmi.sh/core/api/actions/getGasPrice */
export async function getGasPrice<
  config extends Config,
  chainId extends config['chains'][number]['id'],
>(
  config: config,
  parameters: GetGasPriceParameters<config, chainId> = {},
): Promise<GetGasPriceReturnType> {
  const { chainId, ...rest } = parameters
  const client = config.getClient({ chainId })
  const action = getAction(client, viem_getGasPrice, 'getGasPrice')
  return action(rest)
}
