/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import type { FeeValuesType } from 'viem'
import {
  type EstimateFeesPerGasErrorType,
  type EstimateFeesPerGasParameters,
  type EstimateFeesPerGasReturnType,
  estimateFeesPerGas,
} from '../actions/estimateFeesPerGas.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type EstimateFeesPerGasOptions<
  type extends FeeValuesType,
  config extends Config,
> = t.Compute<
  t.ExactPartial<EstimateFeesPerGasParameters<type, config>> & ScopeKeyParameter
>

export function estimateFeesPerGasQueryOptions<
  type extends FeeValuesType = 'eip1559',
  config extends Config,
>(config: config, options: EstimateFeesPerGasOptions<type, config> = {}) {
  return {
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      const result = await estimateFeesPerGas(config, parameters)
      return result ?? null
    },
    queryKey: estimateFeesPerGasQueryKey(options),
  } as const satisfies QueryObserverOptions<
    EstimateFeesPerGasQueryFnData<type>,
    EstimateFeesPerGasErrorType,
    EstimateFeesPerGasData<type>,
    EstimateFeesPerGasQueryFnData<type>,
    EstimateFeesPerGasQueryKey<type, config>
  >
}

export type EstimateFeesPerGasQueryFnData<type extends FeeValuesType> =
  t.Compute<EstimateFeesPerGasReturnType<type>>

export type EstimateFeesPerGasData<type extends FeeValuesType> =
  EstimateFeesPerGasQueryFnData<type>

export function estimateFeesPerGasQueryKey<
  type extends FeeValuesType = 'eip1559',
  config extends Config,
>(options: EstimateFeesPerGasOptions<type, config> = {}) {
  return ['estimateFeesPerGas', filterQueryOptions(options)] as const
}

export type EstimateFeesPerGasQueryKey<
  type extends FeeValuesType,
  config extends Config,
> = ReturnType<typeof estimateFeesPerGasQueryKey<type, config>>
