/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetCapabilitiesErrorType,
  type GetCapabilitiesParameters,
  type GetCapabilitiesReturnType,
  getCapabilities,
} from '../actions/getCapabilities.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetCapabilitiesOptions<
  config extends Config,
  chainId extends config['chains'][number]['id'] | undefined,
> = t.Compute<
  t.ExactPartial<GetCapabilitiesParameters<config, chainId>> & ScopeKeyParameter
>

export function getCapabilitiesQueryOptions<
  config extends Config = Config,
  chainId extends config['chains'][number]['id'] | undefined = undefined,
>(config: config, options: GetCapabilitiesOptions<config, chainId> = {}) {
  return {
    enabled: Boolean(options.connector),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!options.connector) throw new Error('connector is required')
      const result = await getCapabilities(config, {
        ...parameters,
        connector: options.connector,
      })
      return result ?? null
    },
    queryKey: getCapabilitiesQueryKey(options),
  } as const satisfies QueryObserverOptions<
    GetCapabilitiesQueryFnData<config, chainId>,
    GetCapabilitiesErrorType,
    GetCapabilitiesData<config, chainId>,
    GetCapabilitiesQueryFnData<config, chainId>,
    GetCapabilitiesQueryKey<config, chainId>
  >
}

export type GetCapabilitiesQueryFnData<
  config extends Config,
  chainId extends config['chains'][number]['id'] | undefined,
> = t.Compute<GetCapabilitiesReturnType<config, chainId>>

export type GetCapabilitiesData<
  config extends Config,
  chainId extends config['chains'][number]['id'] | undefined,
> = GetCapabilitiesQueryFnData<config, chainId>

export function getCapabilitiesQueryKey<
  config extends Config = Config,
  chainId extends config['chains'][number]['id'] | undefined = undefined,
>(options: GetCapabilitiesOptions<config, chainId> = {}) {
  return [
    'getCapabilities',
    filterQueryOptions({ ...options, connectorUid: options.connector?.uid }),
  ] as const
}

export type GetCapabilitiesQueryKey<
  config extends Config,
  chainId extends config['chains'][number]['id'] | undefined,
> = ReturnType<typeof getCapabilitiesQueryKey<config, chainId>>
