/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetCallsStatusErrorType,
  type GetCallsStatusParameters,
  type GetCallsStatusReturnType,
  getCallsStatus,
} from '../actions/getCallsStatus.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetCallsStatusOptions<config extends Config> = t.Compute<
  t.ExactPartial<GetCallsStatusParameters<config>> & ScopeKeyParameter
>

export function getCallsStatusQueryOptions<config extends Config>(
  config: config,
  options: GetCallsStatusOptions<config> = {},
) {
  return {
    enabled: Boolean(options.id && options.connector),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!parameters.id) throw new Error('id is required')
      if (!options.connector) throw new Error('connector is required')
      const result = await getCallsStatus(config, {
        ...parameters,
        id: parameters.id,
        connector: options.connector,
      })
      return result ?? null
    },
    queryKey: getCallsStatusQueryKey(options),
  } as const satisfies QueryObserverOptions<
    GetCallsStatusQueryFnData,
    GetCallsStatusErrorType,
    GetCallsStatusData,
    GetCallsStatusQueryFnData,
    GetCallsStatusQueryKey<config>
  >
}

export type GetCallsStatusQueryFnData = t.Compute<GetCallsStatusReturnType>

export type GetCallsStatusData = GetCallsStatusQueryFnData

export function getCallsStatusQueryKey<config extends Config>(
  options: GetCallsStatusOptions<config> = {},
) {
  return [
    'getCallsStatus',
    filterQueryOptions({ ...options, connectorUid: options.connector?.uid }),
  ] as const
}

export type GetCallsStatusQueryKey<config extends Config> = ReturnType<
  typeof getCallsStatusQueryKey<config>
>
