/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetEnsAvatarErrorType,
  type GetEnsAvatarParameters,
  type GetEnsAvatarReturnType,
  getEnsAvatar,
} from '../actions/getEnsAvatar.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetEnsAvatarOptions<config extends Config> = t.Compute<
  t.ExactPartial<GetEnsAvatarParameters<config>> & ScopeKeyParameter
>

export function getEnsAvatarQueryOptions<config extends Config>(
  config: config,
  options: GetEnsAvatarOptions<config> = {},
) {
  return {
    enabled: Boolean(options.name),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!parameters.name) throw new Error('name is required')
      const result = await getEnsAvatar(config, {
        ...parameters,
        name: parameters.name,
      })
      return result ?? null
    },
    queryKey: getEnsAvatarQueryKey(options),
  } as const satisfies QueryObserverOptions<
    GetEnsAvatarQueryFnData,
    GetEnsAvatarErrorType,
    GetEnsAvatarData,
    GetEnsAvatarQueryFnData,
    GetEnsAvatarQueryKey<config>
  >
}

export type GetEnsAvatarQueryFnData = t.Compute<GetEnsAvatarReturnType>

export type GetEnsAvatarData = GetEnsAvatarQueryFnData

export function getEnsAvatarQueryKey<config extends Config>(
  options: GetEnsAvatarOptions<config> = {},
) {
  return ['getEnsAvatar', filterQueryOptions(options)] as const
}

export type GetEnsAvatarQueryKey<config extends Config> = ReturnType<
  typeof getEnsAvatarQueryKey<config>
>
