/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetEnsResolverErrorType,
  type GetEnsResolverParameters,
  type GetEnsResolverReturnType,
  getEnsResolver,
} from '../actions/getEnsResolver.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetEnsResolverOptions<config extends Config> = t.Compute<
  t.ExactPartial<GetEnsResolverParameters<config>> & ScopeKeyParameter
>

export function getEnsResolverQueryOptions<config extends Config>(
  config: config,
  options: GetEnsResolverOptions<config> = {},
) {
  return {
    enabled: Boolean(options.name),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!parameters.name) throw new Error('name is required')
      const result = await getEnsResolver(config, {
        ...parameters,
        name: parameters.name,
      })
      return result ?? null
    },
    queryKey: getEnsResolverQueryKey(options),
  } as const satisfies QueryObserverOptions<
    GetEnsResolverQueryFnData,
    GetEnsResolverErrorType,
    GetEnsResolverData,
    GetEnsResolverQueryFnData,
    GetEnsResolverQueryKey<config>
  >
}

export type GetEnsResolverQueryFnData = t.Compute<GetEnsResolverReturnType>

export type GetEnsResolverData = GetEnsResolverQueryFnData

export function getEnsResolverQueryKey<config extends Config>(
  options: GetEnsResolverOptions<config> = {},
) {
  return ['getEnsResolver', filterQueryOptions(options)] as const
}

export type GetEnsResolverQueryKey<config extends Config> = ReturnType<
  typeof getEnsResolverQueryKey<config>
>
