/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetTransactionReceiptErrorType,
  type GetTransactionReceiptParameters,
  type GetTransactionReceiptReturnType,
  getTransactionReceipt,
} from '../actions/getTransactionReceipt.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetTransactionReceiptOptions<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = t.Compute<
  t.ExactPartial<GetTransactionReceiptParameters<config, chainId>> &
    ScopeKeyParameter
>

export function getTransactionReceiptQueryOptions<
  config extends Config,
  chainId extends config['chains'][number]['id'],
>(config: config, options: GetTransactionReceiptOptions<config, chainId> = {}) {
  return {
    enabled: Boolean(options.hash),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!parameters.hash) throw new Error('hash is required')
      const result = await getTransactionReceipt(config, {
        ...parameters,
        hash: parameters.hash,
      })
      return result ?? null
    },
    queryKey: getTransactionReceiptQueryKey(options),
  } as const satisfies QueryObserverOptions<
    GetTransactionReceiptQueryFnData<config, chainId>,
    GetTransactionReceiptErrorType,
    GetTransactionReceiptData<config, chainId>,
    GetTransactionReceiptQueryFnData<config, chainId>,
    GetTransactionReceiptQueryKey<config, chainId>
  >
}

export type GetTransactionReceiptQueryFnData<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = t.Compute<GetTransactionReceiptReturnType<config, chainId>>

export type GetTransactionReceiptData<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = GetTransactionReceiptQueryFnData<config, chainId>

export function getTransactionReceiptQueryKey<
  config extends Config,
  chainId extends config['chains'][number]['id'],
>(options: GetTransactionReceiptOptions<config, chainId> = {}) {
  return ['getTransactionReceipt', filterQueryOptions(options)] as const
}

export type GetTransactionReceiptQueryKey<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = ReturnType<typeof getTransactionReceiptQueryKey<config, chainId>>
