/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetTransactionCountErrorType,
  type GetTransactionCountParameters,
  type GetTransactionCountReturnType,
  getTransactionCount,
} from '../actions/getTransactionCount.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetTransactionCountOptions<config extends Config> = t.Compute<
  t.ExactPartial<GetTransactionCountParameters<config>> & ScopeKeyParameter
>

export function getTransactionCountQueryOptions<config extends Config>(
  config: config,
  options: GetTransactionCountOptions<config> = {},
) {
  return {
    enabled: Boolean(options.address),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!parameters.address) throw new Error('address is required')
      const result = await getTransactionCount(config, {
        ...parameters,
        address: parameters.address,
      })
      return result ?? null
    },
    queryKey: getTransactionCountQueryKey(options),
  } as const satisfies QueryObserverOptions<
    GetTransactionCountQueryFnData,
    GetTransactionCountErrorType,
    GetTransactionCountData,
    GetTransactionCountQueryFnData,
    GetTransactionCountQueryKey<config>
  >
}

export type GetTransactionCountQueryFnData =
  t.Compute<GetTransactionCountReturnType>

export type GetTransactionCountData = GetTransactionCountQueryFnData

export function getTransactionCountQueryKey<config extends Config>(
  options: GetTransactionCountOptions<config> = {},
) {
  return ['getTransactionCount', filterQueryOptions(options)] as const
}

export type GetTransactionCountQueryKey<config extends Config> = ReturnType<
  typeof getTransactionCountQueryKey<config>
>
