/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetTransactionConfirmationsErrorType,
  type GetTransactionConfirmationsParameters,
  type GetTransactionConfirmationsReturnType,
  getTransactionConfirmations,
} from '../actions/getTransactionConfirmations.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetTransactionConfirmationsOptions<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = t.UnionExactPartial<
  GetTransactionConfirmationsParameters<config, chainId>
> &
  ScopeKeyParameter

export function getTransactionConfirmationsQueryOptions<
  config extends Config,
  chainId extends config['chains'][number]['id'],
>(
  config: config,
  options: GetTransactionConfirmationsOptions<config, chainId> = {} as never,
) {
  return {
    enabled: Boolean(options.hash && options.transactionReceipt),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!parameters.hash) throw new Error('hash is required')
      if (!parameters.transactionReceipt)
        throw new Error('transactionReceipt is required')
      const result = await getTransactionConfirmations(config, {
        ...(parameters as any),
        hash: parameters.hash,
        transactionReceipt: parameters.transactionReceipt,
      })
      return result ?? null
    },
    queryKey: getTransactionConfirmationsQueryKey(options),
  } as const satisfies QueryObserverOptions<
    GetTransactionConfirmationsQueryFnData,
    GetTransactionConfirmationsErrorType,
    GetTransactionConfirmationsData,
    GetTransactionConfirmationsQueryFnData,
    GetTransactionConfirmationsQueryKey<config, chainId>
  >
}

export type GetTransactionConfirmationsQueryFnData =
  t.Compute<GetTransactionConfirmationsReturnType>

export type GetTransactionConfirmationsData =
  GetTransactionConfirmationsQueryFnData

export function getTransactionConfirmationsQueryKey<
  config extends Config,
  chainId extends config['chains'][number]['id'],
>(options: GetTransactionConfirmationsOptions<config, chainId> = {} as never) {
  return ['getTransactionConfirmations', filterQueryOptions(options)] as const
}

export type GetTransactionConfirmationsQueryKey<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = ReturnType<typeof getTransactionConfirmationsQueryKey<config, chainId>>
