/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type GetWalletClientErrorType,
  type GetWalletClientParameters,
  type GetWalletClientReturnType,
  getWalletClient,
} from '../actions/getWalletClient.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type GetWalletClientOptions<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = t.Compute<
  t.ExactPartial<GetWalletClientParameters<config, chainId>> & ScopeKeyParameter
>

export function getWalletClientQueryOptions<
  config extends Config,
  chainId extends config['chains'][number]['id'],
>(config: config, options: GetWalletClientOptions<config, chainId> = {}) {
  return {
    enabled: Boolean(options.connector?.getProvider),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!options.connector?.getProvider)
        throw new Error('connector is required')
      const result = await getWalletClient(config, {
        ...parameters,
        connector: options.connector,
      })
      return (result ?? null) as unknown as GetWalletClientData<config, chainId>
    },
    queryKey: getWalletClientQueryKey(options),
    gcTime: 0,
    staleTime: Number.POSITIVE_INFINITY,
  } as const satisfies QueryObserverOptions<
    GetWalletClientQueryFnData<config, chainId>,
    GetWalletClientErrorType,
    GetWalletClientData<config, chainId>,
    GetWalletClientQueryFnData<config, chainId>,
    GetWalletClientQueryKey<config, chainId>
  >
}

export type GetWalletClientQueryFnData<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = t.Compute<GetWalletClientReturnType<config, chainId>>

export type GetWalletClientData<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = GetWalletClientQueryFnData<config, chainId>

export function getWalletClientQueryKey<
  config extends Config,
  chainId extends config['chains'][number]['id'],
>(options: GetWalletClientOptions<config, chainId> = {}) {
  return [
    'getWalletClient',
    filterQueryOptions({ ...options, connectorUid: options.connector?.uid }),
  ] as const
}

export type GetWalletClientQueryKey<
  config extends Config,
  chainId extends config['chains'][number]['id'],
> = ReturnType<typeof getWalletClientQueryKey<config, chainId>>
