/* generated by scripts/codegen */
import type { QueryObserverOptions } from '@tanstack/query-core'
import {
  type WaitForCallsStatusErrorType,
  type WaitForCallsStatusParameters,
  type WaitForCallsStatusReturnType,
  waitForCallsStatus,
} from '../actions/waitForCallsStatus.js'
import type { Config } from '../createConfig.js'
import type { ScopeKeyParameter } from '../types/properties.js'
import type * as t from '../types/utils.js'
import { filterQueryOptions } from './utils.js'

export type WaitForCallsStatusOptions<config extends Config> = t.Compute<
  t.ExactPartial<WaitForCallsStatusParameters<config>> & ScopeKeyParameter
>

export function waitForCallsStatusQueryOptions<config extends Config>(
  config: config,
  options: WaitForCallsStatusOptions<config> = {},
) {
  return {
    enabled: Boolean(options.id && options.connector),
    queryFn: async (context) => {
      const { scopeKey: _, ...parameters } = context.queryKey[1]
      if (!parameters.id) throw new Error('id is required')
      if (!options.connector) throw new Error('connector is required')
      const result = await waitForCallsStatus(config, {
        ...parameters,
        id: parameters.id,
        connector: options.connector,
      })
      return (result ?? null) as unknown as WaitForCallsStatusData
    },
    queryKey: waitForCallsStatusQueryKey(options),
  } as const satisfies QueryObserverOptions<
    WaitForCallsStatusQueryFnData,
    WaitForCallsStatusErrorType,
    WaitForCallsStatusData,
    WaitForCallsStatusQueryFnData,
    WaitForCallsStatusQueryKey<config>
  >
}

export type WaitForCallsStatusQueryFnData =
  t.Compute<WaitForCallsStatusReturnType>

export type WaitForCallsStatusData = WaitForCallsStatusQueryFnData

export function waitForCallsStatusQueryKey<config extends Config>(
  options: WaitForCallsStatusOptions<config> = {},
) {
  return [
    'waitForCallsStatus',
    filterQueryOptions({ ...options, connectorUid: options.connector?.uid }),
  ] as const
}

export type WaitForCallsStatusQueryKey<config extends Config> = ReturnType<
  typeof waitForCallsStatusQueryKey<config>
>
